export const INVITE_LANDING_COPY = {
  accountCreationNote: "Joining will create your account, or log you in.",
  alreadyMemberSignIn: "Already a member? Sign in",
  currentlyPickingHeading: "Currently picking",
  duePrefix: "Due ",
  heading: "You've been invited to",
  invitedBy: "invited by",
  joinButton: "Join group",
  joiningButton: "Joining…",
  memberOverflowSuffix: " more",
  memberPlural: "members",
  memberSingular: "member",
  pickOpen: "Open",
  signInDifferentAccount: "Sign in to a different account",
  whoIsInAvatarGroupLabel: "Group members",
  whoIsInHeading: "Who's in",
} as const;
