export const GROUP_DETAIL_COPY = {
  adminChip: "Admin",
  closedBadge: "closed",
  closedSection: "Closed",
  copiedButton: "Copied!",
  copyButton: "Copy",
  creatorChip: "Creator",
  errors: {
    adminAction: "Failed to update admin status. Please try again.",
    default: "Failed to leave group. Please try again.",
    lastMember: "You are the only member — groups cannot be left empty.",
  },
  expiresAtLabel: "Expires",
  generateButton: "Generate Invite Link",
  groupModeLabel: "Group (30 days, multi-use)",
  inviteErrors: {
    default: "Something went wrong. Please try again.",
  },
  inviteLabel: "Invite Link",
  leaveButton: "Leave Group",
  makeAdminAction: "Make admin",
  memberSingularLabel: "member",
  membersHeading: "Members",
  membersLabel: "members",
  noPicksMessage: "No picks yet. Start one from the Categories tab.",
  notFound: "Group not found.",
  openBadge: "open",
  openSection: "Open",
  personalModeLabel: "Personal (7 days, single-use)",
  regenerateButton: "Revoke & Regenerate",
  regeneratingButton: "Regenerating…",
  revokeAdminAction: "Revoke admin",
  saveExpiryButton: "Save Expiry",
  setExpiryLabel: "Set expiry date",
  settingExpiryButton: "Saving…",
  tabs: {
    categories: "Categories",
    members: "Members",
    picks: "Picks",
  },
} as const;

export const CATEGORY_LIST_COPY = {
  addButton: "Add Category",
  addCategoryLabel: "New category name",
  addCategoryPlaceholder: "e.g. Best Movie",
  addingButton: "Adding…",
  deleteButton: "Delete",
  deletingButton: "Deleting…",
  empty: "No categories yet.",
  errors: {
    create: "Failed to add category.",
    delete: "Failed to delete category.",
    hasPicks:
      "Cannot delete a category that has picks. Remove all picks first.",
  },
  title: "Categories",
} as const;
