export const CATEGORY_COPY = {
  categoriesHeading: "Categories",
  noCategoriesMessage: "No categories yet.",
  addCategoryButton: "Add Category",
  addPickButton: "+ Pick",
  editButton: "Edit",
  cancelButton: "Cancel",
  saveButton: "Save",
  createForm: {
    title: "Add Category",
    nameLabel: "Category Name",
    namePlaceholder: "e.g. Best Movies",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Describe what this category is about",
    submitButton: "Add Category",
    cancelButton: "Cancel",
  },
  editForm: {
    title: "Edit Category",
    nameLabel: "Category Name",
    namePlaceholder: "e.g. Best Movies",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Describe what this category is about",
    submitButton: "Save Changes",
    cancelButton: "Cancel",
  },
  createPickForm: {
    title: "Create Pick",
    categoryLabel: "Category",
    nameLabel: "Name",
    namePlaceholder: "e.g. The Shawshank Redemption",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Add context for this pick",
    topCountLabel: "Top N",
    dueDateLabel: "Due date",
    submitButton: "Create Pick",
    cancelButton: "Cancel",
  },
  errors: {
    default: "Something went wrong. Please try again.",
  },
} as const;
