export const CATEGORY_COPY = {
  addCategoryButton: "Add Category",
  cancelButton: "Cancel",
  categoriesHeading: "Categories",
  createPickButton: "Create Pick",
  editButton: "Edit",
  noCategoriesMessage: "No categories yet.",
  noPicksMessage: "No picks yet.",
  saveButton: "Save",
  createForm: {
    title: "Add Category",
    nameLabel: "Category Name",
    namePlaceholder: "e.g. Best Movies",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Describe what this category is about",
    submitButton: "Add Category",
    cancelButton: "Cancel",
  },
  editForm: {
    title: "Edit Category",
    nameLabel: "Category Name",
    namePlaceholder: "e.g. Best Movies",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Describe what this category is about",
    submitButton: "Save Changes",
    cancelButton: "Cancel",
  },
  errors: {
    default: "Something went wrong. Please try again.",
  },
} as const;
